import nodeResolve from "@rollup/plugin-node-resolve";
import sourcemaps from "rollup-plugin-sourcemaps";

const mainEsm = {
  input: "./lib/main/index.js",
  output: {
    file: "./dist/swim-maps.mjs",
    format: "esm",
    globals: {
      "leaflet": "L",
      "mapbox-gl": "mapboxgl",
    },
    paths: {
      "@swim/util": "@swim/core",
      "@swim/codec": "@swim/core",
      "@swim/fastener": "@swim/core",
      "@swim/collections": "@swim/core",
      "@swim/constraint": "@swim/core",
      "@swim/structure": "@swim/core",
      "@swim/streamlet": "@swim/core",
      "@swim/dataflow": "@swim/core",
      "@swim/recon": "@swim/core",
      "@swim/uri": "@swim/core",
      "@swim/math": "@swim/core",
      "@swim/geo": "@swim/core",
      "@swim/time": "@swim/core",
      "@swim/warp": "@swim/host",
      "@swim/client": "@swim/host",
      "@swim/model": "@swim/ui",
      "@swim/style": "@swim/ui",
      "@swim/theme": "@swim/ui",
      "@swim/view": "@swim/ui",
      "@swim/dom": "@swim/ui",
      "@swim/graphics": "@swim/ui",
      "@swim/controller": "@swim/ui",
    },
    sourcemap: true,
  },
  external: [
    "@swim/util",
    "@swim/codec",
    "@swim/fastener",
    "@swim/collections",
    "@swim/constraint",
    "@swim/structure",
    "@swim/streamlet",
    "@swim/dataflow",
    "@swim/recon",
    "@swim/uri",
    "@swim/math",
    "@swim/geo",
    "@swim/time",
    "@swim/core",
    "@swim/warp",
    "@swim/client",
    "@swim/host",
    "@swim/model",
    "@swim/style",
    "@swim/theme",
    "@swim/view",
    "@swim/dom",
    "@swim/graphics",
    "@swim/controller",
    "@swim/ui",
    "leaflet",
    "mapbox-gl",
    "tslib",
  ],
  plugins: [
    nodeResolve({moduleDirectories: ["../..", "node_modules"]}),
    sourcemaps(),
  ],
  onwarn(warning, warn) {
    if (warning.code === "CIRCULAR_DEPENDENCY") return;
    warn(warning);
  },
};

const mainUmd = {
  input: "./lib/main/index.js",
  output: {
    file: "./dist/swim-maps.js",
    name: "swim",
    format: "umd",
    globals: {
      "@swim/util": "swim",
      "@swim/codec": "swim",
      "@swim/fastener": "swim",
      "@swim/collections": "swim",
      "@swim/constraint": "swim",
      "@swim/structure": "swim",
      "@swim/streamlet": "swim",
      "@swim/dataflow": "swim",
      "@swim/recon": "swim",
      "@swim/uri": "swim",
      "@swim/math": "swim",
      "@swim/geo": "swim",
      "@swim/time": "swim",
      "@swim/core": "swim",
      "@swim/warp": "swim",
      "@swim/client": "swim",
      "@swim/host": "swim",
      "@swim/model": "swim",
      "@swim/style": "swim",
      "@swim/theme": "swim",
      "@swim/view": "swim",
      "@swim/dom": "swim",
      "@swim/graphics": "swim",
      "@swim/controller": "swim",
      "@swim/ui": "swim",
      "leaflet": "L",
      "mapbox-gl": "mapboxgl",
    },
    paths: {
      "@swim/util": "@swim/core",
      "@swim/codec": "@swim/core",
      "@swim/fastener": "@swim/core",
      "@swim/collections": "@swim/core",
      "@swim/constraint": "@swim/core",
      "@swim/structure": "@swim/core",
      "@swim/streamlet": "@swim/core",
      "@swim/dataflow": "@swim/core",
      "@swim/recon": "@swim/core",
      "@swim/uri": "@swim/core",
      "@swim/math": "@swim/core",
      "@swim/geo": "@swim/core",
      "@swim/time": "@swim/core",
      "@swim/warp": "@swim/host",
      "@swim/client": "@swim/host",
      "@swim/model": "@swim/ui",
      "@swim/style": "@swim/ui",
      "@swim/theme": "@swim/ui",
      "@swim/view": "@swim/ui",
      "@swim/dom": "@swim/ui",
      "@swim/graphics": "@swim/ui",
      "@swim/controller": "@swim/ui",
    },
    sourcemap: true,
    interop: "esModule",
    extend: true,
  },
  external: [
    "@swim/util",
    "@swim/codec",
    "@swim/fastener",
    "@swim/collections",
    "@swim/constraint",
    "@swim/structure",
    "@swim/streamlet",
    "@swim/dataflow",
    "@swim/recon",
    "@swim/uri",
    "@swim/math",
    "@swim/geo",
    "@swim/time",
    "@swim/core",
    "@swim/warp",
    "@swim/client",
    "@swim/host",
    "@swim/model",
    "@swim/style",
    "@swim/theme",
    "@swim/view",
    "@swim/dom",
    "@swim/graphics",
    "@swim/controller",
    "@swim/ui",
    "leaflet",
    "mapbox-gl",
  ],
  plugins: [
    nodeResolve({moduleDirectories: ["../..", "node_modules"]}),
    sourcemaps(),
  ],
  onwarn(warning, warn) {
    if (warning.code === "CIRCULAR_DEPENDENCY") return;
    warn(warning);
  },
};

const targets = [mainEsm, mainUmd];
targets.main = [mainEsm, mainUmd];
export default targets;
