# Nightly build that runs all tests and benchmarks on the master branch only with a removed timeout
# This build does not fail on checkstyle violations.

trigger: none

schedules:
  - cron: "0 0 * * *"
    displayName: Daily midnight build
    branches:
      include:
        - master

# Below is from the 'azure-pipelines.yml' file due to lack of an import system in YAML.
# The build timeout limit has been removed as this build has a limit of six hours
strategy:
  matrix:

    jdk8_windows_s2012:
      imageName: "vs2015-win2012r2"
      jdk_version: "1.8"

    jdk8_windows_s2016:
      imageName: "vs2017-win2016"
      jdk_version: "1.8"
    jdk11_windows_s2016:
      imageName: "vs2017-win2016"
      jdk_version: "1.11"

    jdk8_macOS_HighSierra:
      imageName: "macOS-10.13"
      jdk_version: "1.8"
    jdk11_macOS_HighSierra:
      imageName: "macOS-10.13"
      jdk_version: "1.11"

    jdk8_macOS_Mojave:
      imageName: "macOS-10.14"
      jdk_version: "1.8"
    jdk11_macOS_Mojave:
      imageName: "macOS-10.14"
      jdk_version: "1.11"

    jdk8_ubuntu_16:
      imageName: "ubuntu-16.04"
      jdk_version: "1.8"
    jdk11_ubuntu_16:
      imageName: "ubuntu-16.04"
      jdk_version: "1.11"

    jdk8_ubuntu_18:
      imageName: "ubuntu-18.04"
      jdk_version: "1.8"
    jdk11_ubuntu_18:
      imageName: "ubuntu-18.04"
      jdk_version: "1.11"

  maxParallel: 10

pool:
  vmImage: $(imageName)

steps:
  - task: Gradle@2
    inputs:
      workingDirectory: ''
      gradleWrapperFile: 'gradlew'
      gradleOptions: '-Xmx3072m'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: $(jdk_version)
      jdkArchitectureOption: 'x64'
      publishJUnitResults: true
      testResultsFiles: '**/TEST-*.xml'

      #      --info: Display assertion information
      #      --continue: Continue testing after errors
      #      -Pslow: Run tests in the 'slow' group
      #      -Pbenchmark: Run tests in the 'benchmark' group
      #      --debug: Display Gradle messages at the 'debug' level
      tasks: 'test --info --continue -Pslow -PbuildServer -Pbenchmark'
